-- MySQL Script generated by MySQL Workbench
-- Mon Dec 11 22:34:25 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema campaidb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema campaidb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `campaidb` DEFAULT CHARACTER SET utf8 ;
USE `campaidb` ;

-- -----------------------------------------------------
-- Table `campaidb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campaidb`.`user` (
  `id` VARCHAR(10) NOT NULL,
  `Usname` VARCHAR(20) NOT NULL,
  `pwd` VARCHAR(16) NULL,
  `className` VARCHAR(12) NULL,
  `position` VARCHAR(10) NULL,
  `errorLogin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Usname_UNIQUE` (`Usname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campaidb`.`campaign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campaidb`.`campaign` (
  `camid` INT NOT NULL AUTO_INCREMENT,
  `caname` VARCHAR(45) NULL,
  `endeadline` DATETIME NOT NULL,
  `startline` DATETIME NOT NULL,
  `endline` DATETIME NOT NULL,
  `describe` VARCHAR(280) NULL,
  PRIMARY KEY (`camid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campaidb`.`roletype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campaidb`.`roletype` (
  `roleid` INT NOT NULL,
  `roname` VARCHAR(45) NULL,
  PRIMARY KEY (`roleid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campaidb`.`doings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campaidb`.`doings` (
  `doid` INT NOT NULL,
  `dodescribe` VARCHAR(240) NULL,
  `p1` VARCHAR(20) NULL,
  `p2` VARCHAR(20) NULL,
  `p3` VARCHAR(20) NULL,
  `p4` VARCHAR(20) NULL COMMENT '\n',
  `p5` VARCHAR(20) NULL COMMENT '	\n	',
  `p6` VARCHAR(20) NULL,
  `p7` VARCHAR(20) NULL,
  `p8` VARCHAR(20) NULL,
  `p9` VARCHAR(20) NULL,
  `criticURL` VARCHAR(45) NULL,
  `campaign_camid` INT NOT NULL,
  `user_id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`doid`),
  INDEX `fk_doings_campaign1_idx` (`campaign_camid` ASC),
  INDEX `fk_doings_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_doings_campaign1`
    FOREIGN KEY (`campaign_camid`)
    REFERENCES `campaidb`.`campaign` (`camid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doings_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `campaidb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `campaidb`.`party_relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campaidb`.`party_relationship` (
  `party_relationship_id` VARCHAR(10) NOT NULL,
  `party_relationship_ camid` INT NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`party_relationship_id`, `party_relationship_ camid`, `role`),
  INDEX `fk_user_has_campaign_campaign1_idx` (`party_relationship_ camid` ASC),
  INDEX `fk_user_has_campaign_user_idx` (`party_relationship_id` ASC),
  INDEX `fk_party_relationship_roletype1_idx` (`role` ASC),
  CONSTRAINT `fk_user_has_campaign_user`
    FOREIGN KEY (`party_relationship_id`)
    REFERENCES `campaidb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_campaign_campaign1`
    FOREIGN KEY (`party_relationship_ camid`)
    REFERENCES `campaidb`.`campaign` (`camid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_party_relationship_roletype1`
    FOREIGN KEY (`role`)
    REFERENCES `campaidb`.`roletype` (`roleid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
